name: Test GitHub Actions Container

on:
    schedule:
        # cron argument allows to set-up the time when trigger the workflow.
        # This one starts at the beginning of the hour and runs every 1 hour.
        - cron: "20 */1 * * *" # asterisk format in order" minutes, hours, day of month, month, day of the week.

jobs:
    test-workflow-container: # set the workflow name
        runs-on: ubuntu-24.04 # set the GitHub Actions OS to run the job
        container:
          image: portolan75/ubuntu2404_python311_github:prod # set the workflow container to use
        # set the steps to run in the job
        steps:
          # Activate virtualenv. This is to ensure PATH is persistent for all subsequent steps.
          # In fact the PATH is unique to the current step and changes for each step in a job, this avoid that!
          - name: Activate venv + add to PATH
            run: |
              . /opt/LEARN_GITHUB_ACTIONS/bin/activate
              echo PATH=$PATH >> $GITHUB_ENV
          
          # Check If /bin/sh = dash (sh shell) or bash (bash shell)
          - name: Check current default shell
            run: ls -l /bin/sh
            
          - name: Verify Ubuntu/Debian version and architecture
            run: lsb_release -a && echo "Architecture   $(dpkg --print-architecture)"
            
          - name: Verify Python in-use
            run: python3 --version || echo "Python not installed"
            
          # - name: Debug Container State (not running as Docker not installed in the container)
          #   run: docker ps -a
          - name: Test printing some text
            run: echo "Hello World!"
